### ISSUE TITLE
Working out of the box in latest Chrome 86.0

### ISSUE THREAD

**Issue by shailensobhee** [ispras/web-scraper-chrome-extension#74]
Not sure if this project is still being maintained. I just tried to install this extension in the latest Chrome version 86.0.x and there are so many bugs right away:

I get a series of " Uncaught SyntaxError: Cannot use import statement outside a module" . Not sure if Chrome APIs or settings have changed in the last three months (last time this repo was updated). 

Can anyone else confirm my observations?

**Comment by Yatskov** [comment]
We are trying to maintain this extension in a working state on Chrome and Firefox (in dev mode) on Linux. My Chrome version is 86.0.4240.198 and i can't reproduce your issue. Maybe be the problem is in the way ypu install this extension? If so you can read about installation on  [this page](https://github.com/ispras/web-scraper-chrome-extension/blob/master/docs/Installation.md). There is more stable and supported version of similar extension provided by [web scraper company](https://webscraper.io/), but unfortunately it doesn't have features we need.

Also we do not interact with Chrome API directly. Instead of this we use [webextension polyfill](https://www.npmjs.com/package/webextension-polyfill) library. Maybe we could update this library so it could help if Chrome API was updated.

Either way we will apreciate if you can send us more details about your issues.

**Comment by mxsnq** [comment]
Fresh install works fine for me too (Chrome 86.0.4240.198 on Win 10) with both 0.3.704 and 0.3.705 extension releases.
